name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - opencv
  - pip
  - jupyter
  - notebook
  - pip:
    - onnx==1.17.0
    - onnxruntime==1.20.1
    - pillow==11.1.0